// Generated by CoffeeScript 1.6.2
(function() {
  var Event, Injector, UserModel, X_View, Y_View, x, y;

  Injector = require("../src/injector").Injector;

  UserModel = (function() {
    function UserModel() {
      this.x = 3;
    }

    return UserModel;

  })();

  Event = (function() {
    function Event() {
      this.date = new Date;
    }

    return Event;

  })();

  X_View = (function() {
    function X_View() {}

    Injector.register(X_View);

    X_View.inject = {
      model: UserModel,
      event: Event
    };

    return X_View;

  })();

  Y_View = (function() {
    function Y_View() {}

    Injector.register(Y_View);

    Y_View.inject = {
      model: UserModel,
      event: Event
    };

    return Y_View;

  })();

  Injector.mapValue(UserModel);

  Injector.mapSingleton(Event);

  x = new X_View;

  Injector.ensureProperties(x);

  y = new Y_View;

  console.log("x.model", x.model);

  x.model = 3;

  delete x.model;

  console.log("x.model", x.model);

  console.log("y.model", y.model);

  console.log(x.event === y.event);

  Injector.unmap(UserModel);

  console.log(x.model);

  console.log(x.event);

  Injector.unregister(Y_View);

  console.log(y.event);

}).call(this);
